on:
  pull_request:
    branches: [main]

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.setting-vars.outputs.my_var }}
    steps:
      - name: setting-vars
        run: |
          echo "my_var=true" >> '$GITHUB_OUTPUT'
          echo "my_env_var=true" >> '$GITHUB_ENV'
  check-vars:
    runs-on: ubuntu-latest
    needs: vars
    steps:
      - name: check-vars
        run: |
          echo "my_var=${{ needs.vars.outputs.my_var }}"
          echo "my_env_var=${{ env.my_env_var || 'Переменная пустая и не определена' }}"
